# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./exam.h
SOURCES += ./main.cpp \
    ./exam.cpp
FORMS += ./exam.ui
RESOURCES += exam.qrc
